-- BuildSmart Database Schema (Updated with Client Entity)

-- =====================================================
-- 1. Company Table
-- =====================================================
CREATE TABLE company (
    company_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(75) NOT NULL,
    company_address VARCHAR(255) NOT NULL,
    contact_email VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(20) NOT NULL,
    specialization_1 VARCHAR(50) NOT NULL,
    specialization_2 VARCHAR(50),
    specialization_3 VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    company_logo VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 2. Users Table
-- =====================================================
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    middle_name VARCHAR(30),
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_role VARCHAR(20) NOT NULL CHECK (user_role IN ('Owner', 'Admin', 'Estimator', 'Viewer')),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE
);

-- =====================================================
-- 3. Client Table (NEW ADDITION)
-- =====================================================
CREATE TABLE client (
    client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    client_name VARCHAR(100) NOT NULL,
    contact_person VARCHAR(100),
    contact_email VARCHAR(100),
    contact_number VARCHAR(20),
    client_address VARCHAR(255),
    client_type VARCHAR(20) NOT NULL DEFAULT 'New' CHECK (client_type IN ('New', 'Returning')),
    default_downpayment_percentage DECIMAL(5,2) CHECK (default_downpayment_percentage BETWEEN 0 AND 100),
    notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_client_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE
);

-- =====================================================
-- 4. Suppliers Table 
-- =====================================================
CREATE TABLE suppliers (
    supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(100) NOT NULL,
    supplier_address VARCHAR(255) NOT NULL,
    warehouse_loc VARCHAR(100),
    city VARCHAR(60) NOT NULL,
    region VARCHAR(30) NOT NULL CHECK (region IN ('Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'CAR', 'NCR', 'NIR', 'BARMM')),
    contact_email VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(20) NOT NULL,
    supplier_type VARCHAR(30) NOT NULL CHECK (supplier_type IN ('Distributor', 'Warehouse', 'Retailer')),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    average_price_score DECIMAL(5,2) CHECK (average_price_score BETWEEN 0 AND 100),
    update_frequency_score DECIMAL(5,2) CHECK (update_frequency_score BETWEEN 0 AND 100),
    reliability_score DECIMAL(5,2) CHECK (reliability_score BETWEEN 0 AND 100),
    delivery_score DECIMAL(5,2) CHECK (delivery_score BETWEEN 0 AND 100),
    overall_score DECIMAL(5,2) CHECK (overall_score BETWEEN 0 AND 100)
);

-- =====================================================
-- 5. Supplier Region
-- =====================================================
CREATE TABLE supplier_region (
    region_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INT NOT NULL,
    region VARCHAR(30) NOT NULL CHECK (region IN ('Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'CAR', 'NCR', 'NIR', 'BARMM')),
    province VARCHAR(60) NOT NULL,
    city VARCHAR(60) NOT NULL,
    CONSTRAINT fk_supplier_region_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE CASCADE,
    CONSTRAINT uq_supplier_region UNIQUE (supplier_id, region, province, city)
);

-- =====================================================
-- 6. Supplier Discount Rule
-- =====================================================
CREATE TABLE supplier_discount_rule (
    supplierdisc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    supplier_id INT NOT NULL,
    rule_type VARCHAR(30) NOT NULL CHECK (rule_type IN ('Bulk Discount', 'Negotiated Price', 'Minimum Order', 'Preferred Supplier')),
    minimum_order_amount DECIMAL(15,2),
    discount_percentage_rate DECIMAL(5,2) CHECK (discount_percentage_rate BETWEEN 0 AND 100),
    fixed_discount_amount DECIMAL(15,2),
    effective_date DATE NOT NULL,
    expiration_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_supplier_discount_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT fk_supplier_discount_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE CASCADE
);

-- =====================================================
-- 7. Category
-- =====================================================
CREATE TABLE category (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_type VARCHAR(40) NOT NULL CHECK (category_type IN ('Structural', 'Concrete & Masonry', 'Reinforcement & Steel', 'Timber & Lumber', 'Roofing', 'Insulation & Waterproofing', 'Masonry Units & Blocks', 'Doors, Windows & Glazing', 'Finishing', 'Flooring & Tiles', 'Ceilings & Suspended Systems', 'Paints, Coatings & Sealants', 'Plumbing & Pipework', 'HVAC & Mechanical', 'Electrical & Lighting', 'Hardware & Fasteners', 'Adhesives & Tapes', 'Tools, Equipment & Consumables', 'Safety & PPE', 'Landscaping & Siteworks', 'Specialty Materials & Systems', 'Others')),
    category_desc VARCHAR(100) NOT NULL
);

-- =====================================================
-- 8. Items
-- =====================================================
CREATE TABLE items (
    item_code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT NOT NULL,
    company_id INT,
    item_name VARCHAR(100) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    item_source VARCHAR(20) NOT NULL CHECK (item_source IN ('DPWH', 'PSA', 'Supplier', 'Internal')),
    description VARCHAR(255),
    color VARCHAR(50),
    CONSTRAINT fk_items_category FOREIGN KEY (category_id) REFERENCES category(category_id),
    CONSTRAINT fk_items_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE SET NULL
);

-- =====================================================
-- 9. Historical Price Record
-- =====================================================
CREATE TABLE historical_price_record (
    historicalrec_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code INT NOT NULL,
    supplier_id INT,
    price_source VARCHAR(20) NOT NULL CHECK (price_source IN ('DPWH', 'PSA', 'Supplier', 'Internal')),
    region VARCHAR(30) CHECK (region IN ('Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'CAR', 'NCR', 'NIR', 'BARMM')),
    quarter VARCHAR(2) CHECK (quarter IN ('Q1', 'Q2', 'Q3', 'Q4')),
    year SMALLINT CHECK (year >= 2000),
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0),
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historical_price_item FOREIGN KEY (item_code) REFERENCES items(item_code) ON DELETE CASCADE,
    CONSTRAINT fk_historical_price_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE CASCADE,
    CONSTRAINT uq_historical_price UNIQUE (item_code, supplier_id, price_source, quarter, year)
);

-- =====================================================
-- 10. Pricelist Review Item
-- =====================================================
CREATE TABLE pricelist_review_item (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_name VARCHAR(100) NOT NULL,
    raw_unit VARCHAR(30) NOT NULL,
    raw_price DECIMAL(12,2) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    suggested_category_type VARCHAR(40),
    suggested_material VARCHAR(100),
    suggested_brand VARCHAR(100),
    description VARCHAR(255),
    color VARCHAR(50),
    company_id INT,
    upload_id INT,
    source VARCHAR(20) NOT NULL,
    supplier_id INT,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pricelist_review_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE SET NULL,
    CONSTRAINT fk_pricelist_review_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE SET NULL
);

-- =====================================================
-- 11. Approved Match Cache
-- =====================================================
CREATE TABLE approved_match_cache (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT,
    normalized_name VARCHAR(255) NOT NULL,
    normalized_unit VARCHAR(50) NOT NULL,
    item_code INT NOT NULL,
    confirmed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_approved_match_cache_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT fk_approved_match_cache_item FOREIGN KEY (item_code) REFERENCES items(item_code) ON DELETE CASCADE,
    CONSTRAINT uq_approved_match_cache_company_key UNIQUE (company_id, normalized_name, normalized_unit)
);

CREATE INDEX ix_approved_match_cache_normalized_name ON approved_match_cache (normalized_name);
CREATE INDEX ix_approved_match_cache_normalized_unit ON approved_match_cache (normalized_unit);

-- =====================================================
-- 12. Material Price Variance
-- =====================================================
CREATE TABLE material_price_variance (
    mpv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code INT,
    variance_source VARCHAR(20) NOT NULL DEFAULT 'Internal' CHECK (variance_source IN ('Internal', 'PSA')),
    commodity_group VARCHAR(60),
    quarter VARCHAR(2) NOT NULL CHECK (quarter IN ('Q1','Q2','Q3','Q4')),
    year SMALLINT NOT NULL CHECK (year >= 2000),
    percent_change DECIMAL(5,2) NOT NULL,
    trend_direction VARCHAR(10) NOT NULL CHECK (trend_direction IN ('Up', 'Down', 'Stable')),
    is_significant_spike BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_mpv_item FOREIGN KEY (item_code) REFERENCES items(item_code) ON DELETE CASCADE,
    CONSTRAINT uq_material_price_variance UNIQUE (item_code, quarter, year)
);

-- =====================================================
-- 13. Quotation (UPDATED with client_id FK)
-- =====================================================
CREATE TABLE quotation (
    quote_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    user_id INT NOT NULL,
    client_id INT, -- NEW FK FIELD
    project_name VARCHAR(150) NOT NULL,
    project_location VARCHAR(255) NOT NULL,
    project_region VARCHAR(30) NOT NULL CHECK (project_region IN ('Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'CAR', 'NCR', 'NIR', 'BARMM')),
    input_method VARCHAR(30) NOT NULL CHECK (input_method IN ('Manual', 'Blueprint', 'Hybrid')),
    blueprint_file_path VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Final')),
    total_material_cost DECIMAL(15,2) NOT NULL DEFAULT 0 CHECK (total_material_cost >= 0),
    total_service_cost DECIMAL(15,2) NOT NULL DEFAULT 0 CHECK (total_service_cost >= 0),
    grand_total DECIMAL(15,2) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quotation_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT fk_quotation_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_quotation_client FOREIGN KEY (client_id) REFERENCES client(client_id) ON DELETE SET NULL -- NEW FOREIGN KEY CONSTRAINT
);

-- =====================================================
-- 14. Project Segments
-- =====================================================
CREATE TABLE project_segments (
    segment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id INT NOT NULL,
    segment_name VARCHAR(100) NOT NULL,
    segment_type VARCHAR(50) NOT NULL,
    source_method VARCHAR(30) NOT NULL CHECK (source_method IN ('Manual', 'Blueprint', 'Hybrid')),
    floor_level VARCHAR(50) NOT NULL,
    shape_type VARCHAR(50),
    length DECIMAL(10,2) NOT NULL CHECK (length >= 0),
    width DECIMAL(10,2) NOT NULL CHECK (width >= 0),
    area_sqm DECIMAL(12,2) NOT NULL CHECK (area_sqm >= 0),
    polygon_coords TEXT,
    confidence_score DECIMAL(5,2) CHECK (confidence_score BETWEEN 0 AND 100),
    included_in_quote BOOLEAN NOT NULL DEFAULT TRUE,
    scope_of_work VARCHAR(100) NOT NULL,
    work_type VARCHAR(100) NOT NULL,
    notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Removed')),
    CONSTRAINT fk_project_segments_quote FOREIGN KEY (quote_id) REFERENCES quotation(quote_id) ON DELETE CASCADE
);

-- =====================================================
-- 15. Segment Tag
-- =====================================================
CREATE TABLE segment_tag (
    tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id INT NOT NULL,
    tag_type VARCHAR(20) NOT NULL CHECK (tag_type IN ('Preference', 'Condition')),
    tag_value VARCHAR(40) NOT NULL CHECK (
        (tag_type = 'Preference' AND tag_value IN ('Durability', 'Cost Efficiency', 'Aesthetic Finish', 'Low-Maintenance', 'Eco-Friendly'))
        OR
        (tag_type = 'Condition' AND tag_value IN ('Heavy-Rain Exposure', 'High Foot Traffic', 'Crack-prone Surface', 'Moisture Prone Area'))
    ),
    CONSTRAINT fk_segment_tag_segment FOREIGN KEY (segment_id) REFERENCES project_segments(segment_id) ON DELETE CASCADE,
    CONSTRAINT uq_segment_tag UNIQUE (segment_id, tag_type, tag_value)
);

-- =====================================================
-- 16. Quotation Items
-- =====================================================
CREATE TABLE quotation_items (
    quote_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id INT NOT NULL,
    item_code INT NOT NULL,
    supplier_id INT,
    quantity DECIMAL(12,2) NOT NULL CHECK (quantity > 0),
    unit_cost DECIMAL(12,2) NOT NULL CHECK (unit_cost >= 0),
    markup_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (markup_percentage BETWEEN 0 AND 100),
    final_unit_price DECIMAL(15,2) NOT NULL CHECK (final_unit_price >= 0),
    total_cost DECIMAL(15,2) NOT NULL CHECK (total_cost >= 0),
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('DPWH', 'PSA', 'Supplier', 'Internal')),
    source_price_id INT,
    last_refreshed_at TIMESTAMP,
    is_price_locked BOOLEAN NOT NULL DEFAULT FALSE,
    original_unit_cost DECIMAL(12,2),
    CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES quotation(quote_id) ON DELETE CASCADE,
    CONSTRAINT fk_quote_items_item FOREIGN KEY (item_code) REFERENCES items(item_code),
    CONSTRAINT fk_quote_items_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE SET NULL,
    CONSTRAINT fk_quotation_items_source_price FOREIGN KEY (source_price_id) REFERENCES historical_price_record(historicalrec_id) ON DELETE SET NULL,
    CONSTRAINT uq_quote_item UNIQUE (quote_id, item_code)
);

-- =====================================================
-- 17. Quotation Price History
-- =====================================================
CREATE TABLE quotation_price_history (
    price_history_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_item_id INT NOT NULL,
    unit_cost_before DECIMAL(12,2) NOT NULL,
    unit_cost_after DECIMAL(12,2) NOT NULL,
    total_cost_before DECIMAL(15,2),
    total_cost_after DECIMAL(15,2),
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_reason VARCHAR(100) NOT NULL CHECK (changed_reason IN ('Initial Creation', 'Manual Refresh', 'Auto Refresh', 'Manual Override')),
    changed_by_user_id INT,
    CONSTRAINT fk_price_history_quote_item FOREIGN KEY (quote_item_id) REFERENCES quotation_items(quote_item_id) ON DELETE CASCADE,
    CONSTRAINT fk_price_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE INDEX ix_price_history_quote_item ON quotation_price_history(quote_item_id);
CREATE INDEX ix_price_history_changed_at ON quotation_price_history(changed_at);

-- =====================================================
-- 18. Quotation Service Cost
-- =====================================================
CREATE TABLE quotation_service_cost (
    service_cost_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id INT NOT NULL,
    service_type VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    labor_cost DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (labor_cost >= 0),
    equipment_cost DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (equipment_cost >= 0),
    contingency_cost DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (contingency_cost >= 0),
    other_cost DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (other_cost >= 0),
    subtotal DECIMAL(15,2) NOT NULL CHECK (subtotal >= 0),
    CONSTRAINT fk_service_cost_quote FOREIGN KEY (quote_id) REFERENCES quotation(quote_id) ON DELETE CASCADE
);

-- =====================================================
-- 19. Company Rule
-- =====================================================
CREATE TABLE company_rule (
    rule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    rule_name VARCHAR(150) NOT NULL,
    specialization VARCHAR(80) NOT NULL,
    scope_of_work VARCHAR(100) NOT NULL,
    work_type VARCHAR(100) NOT NULL,
    checklist_items TEXT,
    primary_source VARCHAR(30) NOT NULL CHECK (primary_source IN ('Uploaded', 'Supplier', 'Government')),
    secondary_source VARCHAR(30) CHECK (secondary_source IN ('Uploaded', 'Supplier', 'Government')),
    fallback_source VARCHAR(30) CHECK (fallback_source IN ('Uploaded', 'Supplier', 'Government')),
    fallback_rule VARCHAR(100) NOT NULL CHECK (fallback_rule IN ('Lowest Equivalent', 'Nearest', 'Manual')),
    strategy_type VARCHAR(30) NOT NULL CHECK (strategy_type IN ('Practical', 'Standard', 'Premium')),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_rule_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE
);

-- =====================================================
-- 20. Rule Category Detail 
-- =====================================================
CREATE TABLE rule_category_detail (
    rule_id INT PRIMARY KEY,
    category_id INT NOT NULL,
    preferred_item_code INT,
    material_priority SMALLINT NOT NULL DEFAULT 1,
    conversion_factor DECIMAL(12,4) CHECK (conversion_factor > 0),
    wastage_allowance_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (wastage_allowance_percentage BETWEEN 0 AND 100),
    fallback_rule VARCHAR(100),
    CONSTRAINT fk_rule_category_detail_rule FOREIGN KEY (rule_id) REFERENCES company_rule(rule_id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_category_detail_category FOREIGN KEY (category_id) REFERENCES category(category_id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_category_detail_item FOREIGN KEY (preferred_item_code) REFERENCES items(item_code) ON DELETE SET NULL
);

-- =====================================================
-- 21. Rule Labor
-- =====================================================
CREATE TABLE rule_labor (
    rule_id INT PRIMARY KEY,
    region VARCHAR(30) NOT NULL CHECK (region IN ('Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'CAR', 'NCR', 'NIR', 'BARMM')),
    labor_trade VARCHAR(60) NOT NULL,
    labor_rate DECIMAL(12,2) NOT NULL CHECK (labor_rate >= 0),
    productivity_index DECIMAL(6,2),
    fallback_rule VARCHAR(100),
    CONSTRAINT fk_rule_labor_rule FOREIGN KEY (rule_id) REFERENCES company_rule(rule_id) ON DELETE CASCADE
);

-- =====================================================
-- 22. Rule Pricing
-- =====================================================
CREATE TABLE rule_pricing (
    rule_id INT PRIMARY KEY,
    quotation_tier VARCHAR(30) NOT NULL,
    markup_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (markup_percentage BETWEEN 0 AND 100),
    contingency_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (contingency_percentage BETWEEN 0 AND 100),
    overhead_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (overhead_percentage BETWEEN 0 AND 100),
    profit_margin_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (profit_margin_percentage BETWEEN 0 AND 100),
    CONSTRAINT fk_rule_pricing_rule FOREIGN KEY (rule_id) REFERENCES company_rule(rule_id) ON DELETE CASCADE
);

-- =====================================================
-- 23. Scope Template
-- =====================================================
CREATE TABLE scope_template (
    scope_template_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    template_name VARCHAR(150) NOT NULL,
    specialization VARCHAR(80) NOT NULL,
    scope_of_work VARCHAR(100) NOT NULL,
    work_type VARCHAR(100) NOT NULL,
    description TEXT,
    checklist_items TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scope_template_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE
);

-- =====================================================
-- 24. Scope Template Category
-- =====================================================
CREATE TABLE scope_template_category (
    stc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_template_id INT NOT NULL,
    category_id INT NOT NULL,
    CONSTRAINT fk_scope_template_category_template FOREIGN KEY (scope_template_id) REFERENCES scope_template(scope_template_id) ON DELETE CASCADE,
    CONSTRAINT fk_scope_template_category_category FOREIGN KEY (category_id) REFERENCES category(category_id) ON DELETE CASCADE,
    CONSTRAINT uq_scope_template_category UNIQUE (scope_template_id, category_id)
);

-- =====================================================
-- 25. Rule Scope
-- =====================================================
CREATE TABLE rule_scope (
    rule_id INT PRIMARY KEY,
    scope_template_id INT,
    service_specialization VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT fk_rule_scope_rule FOREIGN KEY (rule_id) REFERENCES company_rule(rule_id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_scope_scope_template FOREIGN KEY (scope_template_id) REFERENCES scope_template(scope_template_id) ON DELETE SET NULL
);

-- =====================================================
-- 26. Rule Scope Category 
-- =====================================================
CREATE TABLE rule_scope_category (
    rsc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id INT NOT NULL,
    category_id INT NOT NULL,
    CONSTRAINT fk_rule_scope_category_rule FOREIGN KEY (rule_id) REFERENCES company_rule(rule_id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_scope_category_category FOREIGN KEY (category_id) REFERENCES category(category_id) ON DELETE CASCADE,
    CONSTRAINT uq_rule_scope_category UNIQUE (rule_id, category_id)
);

-- =====================================================
-- 27. Unit Rule
-- =====================================================
CREATE TABLE unit_rule (
    unit_rule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    category_id INT,
    unit_name VARCHAR(50) NOT NULL,
    unit_abbreviation VARCHAR(10) NOT NULL,
    base_unit VARCHAR(50),
    conversion_to_base_unit DECIMAL(12,4) CHECK (conversion_to_base_unit > 0),
    description VARCHAR(255),
    display_order SMALLINT DEFAULT 0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_unit_rule_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT fk_unit_rule_category FOREIGN KEY (category_id) REFERENCES category(category_id) ON DELETE SET NULL,
    CONSTRAINT uq_unit_rule_per_company UNIQUE (company_id, unit_abbreviation, category_id)
);

-- =====================================================
-- 28. Source Priority
-- =====================================================
CREATE TABLE source_priority (
    priority_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    price_source VARCHAR(20) NOT NULL CHECK (price_source IN ('DPWH', 'PSA', 'Supplier', 'Internal')),
    priority_rank INT NOT NULL CHECK (priority_rank >= 1),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_source_priority_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT uq_source_priority UNIQUE (company_id, price_source),
    CONSTRAINT uq_source_priority_rank UNIQUE (company_id, priority_rank)
);

-- =====================================================
-- 29. Processed File Log (REQUIRED FOR SCRAPING PIPELINE)
-- =====================================================
CREATE TABLE processed_file_log (
    file_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('DPWH', 'PSA')),
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) NOT NULL UNIQUE, -- SHA-256 Checksum to prevent duplicates
    quarter VARCHAR(2) CHECK (quarter IN ('Q1', 'Q2', 'Q3', 'Q4')),
    year SMALLINT CHECK (year >= 2000),
    records_processed INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'Success' CHECK (status IN ('Pending', 'Success', 'Failed')),
    error_log TEXT,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 30. Price List Upload Table (NEW ADDITION)
-- =====================================================
CREATE TABLE price_list_upload (
    upload_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) NOT NULL,  -- SHA-256 hash for deduplication
    file_size BIGINT,
    source VARCHAR(20),  -- DPWH, PSA, Supplier, Internal
    supplier_id INT,
    quarter VARCHAR(2) CHECK (quarter IN ('Q1', 'Q2', 'Q3', 'Q4')),
    year SMALLINT CHECK (year >= 2000),
    upload_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),
    records_imported INT,  -- count of rows added to historical_price_record
    error_message TEXT,  -- if processing_status = 'failed'
    CONSTRAINT fk_upload_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT fk_upload_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE SET NULL,
    CONSTRAINT uq_company_file_period UNIQUE (company_id, file_hash, quarter, year)
);

CREATE INDEX idx_upload_company_status ON price_list_upload(company_id, processing_status);
CREATE INDEX idx_upload_file_hash ON price_list_upload(file_hash);
ALTER TABLE pricelist_review_item ADD CONSTRAINT fk_pricelist_review_upload
    FOREIGN KEY (upload_id) REFERENCES price_list_upload(upload_id) ON DELETE CASCADE;
