// Verbatim BuildSmart Terms and Conditions, as provided — do not paraphrase or rewrite
// this content. The only change from the source file is repairing an em-dash character
// that came through as a mis-encoded "â" in the original document; wording is untouched.
// [Insert Date] / [Insert contact email] / [Insert institution...] placeholders are kept
// exactly as given — filling those in is not a frontend decision.
export const TERMS_AND_CONDITIONS = `# BUILDSMART — TERMS AND CONDITIONS

**Effective Date:** [Insert Date]
**Last Updated:** [Insert Date]

---

## PREAMBLE

Welcome to BuildSmart. These Terms and Conditions ("Terms") govern your access to and use of the BuildSmart platform ("the System," "the Platform," "the Service"), an AI-assisted construction quotation and price-management system developed for construction small and medium enterprises (SMEs) operating in the Republic of the Philippines.

By creating an account, checking the acceptance box, or otherwise accessing or using BuildSmart, you ("the User," "you," "your") acknowledge that you have read, understood, and agree to be bound by these Terms. **If you do not agree to these Terms, you must not create an account or use the Service.**

---

## 1. NATURE OF THE SERVICE — DECISION-SUPPORT, NOT AUTHORITATIVE PRICING

### 1.1 What BuildSmart Is
BuildSmart is a **decision-support and estimation tool**. It assists contractors, estimators, and quantity surveyors in generating construction quotations by:
- Processing uploaded blueprints to identify and estimate project segments and areas;
- Computing Bills of Quantities (BOQ) from detected or manually entered measurements;
- Applying user-configured company rules, pricing strategies, and supplier preferences;
- Referencing material price data from government sources and user-uploaded pricelists;
- Presenting historical price trends and comparative supplier information.

### 1.2 What BuildSmart Is NOT
You expressly acknowledge and agree that BuildSmart:
- **Is NOT a procurement marketplace.** The System does not execute purchases, transactions, or business-to-business transfers of any kind.
- **Does NOT negotiate with, contract with, or transact on behalf of suppliers.** Supplier information within the System is reference data only.
- **Does NOT provide professional engineering, architectural, quantity surveying, financial, or legal advice.** Outputs are estimates for your professional consideration, not certified professional opinions.
- **Does NOT guarantee the accuracy, completeness, or currency of any price, quantity, area measurement, or quotation it generates.**

### 1.3 Human Judgment Remains Final
All outputs generated by BuildSmart — including AI-assisted blueprint segmentation, area calculations, price recommendations, material substitutions, and quotation totals — are **provisional estimates requiring independent verification by a qualified human professional**. You remain solely responsible for reviewing, validating, correcting, and approving any quotation before relying upon it, issuing it to a client, or entering into any contractual commitment based upon it.

**BuildSmart is an assistive auditor, not a decision-maker. Final estimation authority rests with you.**

---

## 2. ELIGIBILITY AND ACCOUNT REGISTRATION

### 2.1 Eligibility
To register for and use BuildSmart, you must:
- Be at least eighteen (18) years of age;
- Be legally authorized to represent the construction company or business entity you register on the Platform;
- Provide accurate, current, and complete registration information;
- Not be barred from using the Service under any applicable Philippine law.

### 2.2 Company Accounts and Multi-Tenancy
BuildSmart operates on a multi-tenant model. Each registered company constitutes a separate tenant with isolated data. By registering a company, you warrant that you are duly authorized to do so on that company's behalf and to bind that company to these Terms.

### 2.3 User Roles
Accounts may be assigned roles (Owner, Admin, Estimator, Viewer) carrying differing permissions. Account Owners and Administrators are responsible for the actions of all users they authorize within their company account.

### 2.4 Account Security
You are responsible for:
- Maintaining the confidentiality of your login credentials;
- All activity occurring under your account, whether or not authorized by you;
- Immediately notifying us of any unauthorized access or suspected security breach.

You must not share credentials, permit unauthorized access, or use another user's account.

---

## 3. DATA YOU PROVIDE — OWNERSHIP, LICENSE, AND RESPONSIBILITY

### 3.1 Your Data Remains Yours
You retain all ownership rights in the data you upload to BuildSmart, including:
- Blueprints, architectural drawings, and project documents;
- Supplier pricelists and material catalogs;
- Company pricing rules, markup structures, and negotiated supplier agreements;
- Project records and generated quotations.

Collectively, "Your Data."

### 3.2 Limited License to Operate the Service
You grant BuildSmart a limited, non-exclusive, revocable license to store, process, and display Your Data **solely for the purpose of providing the Service to you**. This license terminates when you delete the data or close your account, subject to Section 10.

### 3.3 Your Warranties Regarding Uploaded Data
By uploading data, you warrant that:
- You own the data or have all necessary rights and permissions to upload it;
- The upload does not infringe any third party's intellectual property, confidentiality, or contractual rights;
- Uploaded blueprints do not violate any non-disclosure agreement or client confidentiality obligation to which you are bound;
- Supplier pricelists were lawfully obtained and you are not prohibited from processing them.

**You are solely responsible for ensuring you have the right to upload any blueprint or pricelist. BuildSmart does not verify your entitlement to the documents you provide.**

### 3.4 Prohibited Data
You must not upload:
- Data containing malware, or intended to compromise the System;
- Personal data of third parties for which you lack a lawful basis to process;
- Content that is unlawful, defamatory, or infringing.

---

## 4. DATA PRIVACY (REPUBLIC ACT NO. 10173)

### 4.1 Compliance Commitment
BuildSmart processes personal information in accordance with the **Data Privacy Act of 2012 (Republic Act No. 10173)**, its Implementing Rules and Regulations, and applicable issuances of the National Privacy Commission (NPC).

### 4.2 Personal Information We Collect
On registration and during use, we collect: name, business email address, contact number, company name, company address, business specialization, company logo (optional), and hashed authentication credentials.

### 4.3 Purpose of Processing
Personal information is processed solely to:
- Authenticate and manage your account;
- Provide, maintain, and improve the Service;
- Isolate your company's data from other tenants;
- Communicate service-related notices.

### 4.4 Your Rights as a Data Subject
Under RA 10173, you have the right to be informed, to object, to access, to rectify, to erasure or blocking, to damages, and to data portability. Requests may be directed to the contact point in Section 13.

### 4.5 Security Measures
We employ hashed credential storage, role-based access control, encrypted transmission (HTTPS/SSL), and tenant data isolation. **However, no system is perfectly secure**, and we cannot guarantee absolute security.

---

## 5. GOVERNMENT AND THIRD-PARTY DATA SOURCES

### 5.1 Sources Used
BuildSmart references publicly published data, including:
- **DPWH Construction Materials Price Data (DPWH-CMPD)** — used as a government reference for material peso prices;
- **Philippine Statistics Authority indices (CMWPI/CMRPI)** — used for market trend and price-movement analysis only, **not as a source of transactable prices**.

### 5.2 No Endorsement or Affiliation
BuildSmart is **not affiliated with, endorsed by, or officially connected to** the Department of Public Works and Highways, the Philippine Statistics Authority, or any government agency. References to published government data do not imply approval, certification, or partnership.

### 5.3 Accuracy and Currency Not Guaranteed
Government price data is published periodically and may be outdated, incomplete, regionally inapplicable, or superseded at any time. **BuildSmart does not warrant that any referenced government figure reflects current market prices.** Reference prices are indicative only.

### 5.4 Lawful Data Ingestion
Where BuildSmart retrieves publicly published data, it does so in a manner intended to comply with the **Cybercrime Prevention Act of 2012 (Republic Act No. 10175)** and applicable NPC guidance on automated data collection. BuildSmart does not access private, credentialed, or protected systems without authorization.

---

## 6. ARTIFICIAL INTELLIGENCE — LIMITATIONS AND ACKNOWLEDGMENTS

### 6.1 AI Is Assistive, Not Authoritative
BuildSmart employs artificial intelligence (including third-party AI services) to assist with blueprint interpretation, material name normalization, price discrepancy flagging, and interpretive market commentary.

### 6.2 You Acknowledge AI Limitations
You expressly acknowledge that AI-generated outputs:
- **May be inaccurate, incomplete, or wrong**, including in ways that are not obvious;
- May misidentify rooms, segments, or areas within a blueprint;
- May misclassify or mismatch materials;
- May produce confidence scores that do not reliably indicate correctness;
- **Must be independently verified before any reliance is placed upon them.**

### 6.3 Market Intelligence Is Interpretive, Not Predictive
Market intelligence features present **interpretive summaries of historical price movement**. They are **not financial forecasts, investment advice, or predictions of future prices**, and must not be relied upon as such.

### 6.4 Blueprint Segmentation Requires Human Confirmation
Automated blueprint segmentation produces **provisional** area estimates. You are required to review, correct, and confirm all detected segments before quotation generation. **BuildSmart accepts no liability for area miscalculations arising from unverified automated segmentation.**

---

## 7. COMPETITION AND ANTI-COLLUSION (REPUBLIC ACT NO. 10667)

### 7.1 Prohibited Use
BuildSmart is designed with tenant data isolation specifically to prevent the aggregation of competitor pricing into anti-competitive outcomes. You must **not**:
- Use the Service to coordinate pricing, bids, or market allocation with competitors;
- Attempt to access, infer, or extract another tenant's pricing data, markup structures, or supplier agreements;
- Use the Service in any manner constituting a prohibited agreement, abuse of dominance, or anti-competitive conduct under the **Philippine Competition Act (Republic Act No. 10667)**.

### 7.2 No Cross-Tenant Price Sharing
BuildSmart does not disclose, pool, or publish one company's proprietary pricing, markup, or negotiated supplier terms to any other company.

---

## 8. ACCEPTABLE USE

You must not:
- Reverse engineer, decompile, or attempt to derive the System's source code or AI models;
- Circumvent authentication, access controls, rate limits, or tenant isolation;
- Introduce malware or attempt unauthorized access (which may constitute an offense under RA 10175);
- Scrape, bulk-extract, or resell data obtained from the Service;
- Use the Service to generate fraudulent quotations or misrepresent costs to clients or government agencies;
- Impersonate another person, company, or entity;
- Use the Service for any unlawful purpose.

Violation may result in immediate suspension or termination.

---

## 9. DISCLAIMER OF WARRANTIES

**THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.**

To the fullest extent permitted by Philippine law, BuildSmart disclaims all warranties, including any warranty of merchantability, fitness for a particular purpose, accuracy, and non-infringement.

**Without limiting the foregoing, BuildSmart does not warrant that:**
- Any quotation, price, area measurement, or Bill of Quantities generated is accurate, complete, or fit for any purpose;
- Referenced material prices reflect actual current market prices;
- AI-assisted outputs are correct;
- The Service will be uninterrupted, secure, or error-free;
- Any defect will be corrected.

**You use BuildSmart's outputs entirely at your own professional risk.**

---

## 10. LIMITATION OF LIABILITY

### 10.1 Exclusion of Consequential Damages
To the maximum extent permitted by law, BuildSmart, its developers, and its academic institution shall **not** be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including without limitation:
- Loss of profit, revenue, business, or contracts;
- Cost overruns on any construction project;
- Losses arising from an underquoted or overquoted bid;
- Losses arising from reliance on an inaccurate area measurement, material price, or AI-generated output;
- Loss of data;
- Reputational harm.

**This exclusion applies even if BuildSmart was advised of the possibility of such damages.**

### 10.2 Your Assumption of Estimation Risk
**Construction estimation carries inherent financial risk.** You acknowledge that quotations generated by BuildSmart are estimates requiring your professional verification, and that **any commercial decision, bid, tender, or contract you enter into based upon a BuildSmart output is made solely at your own risk and on your own professional judgment.**

### 10.3 Prototype / Academic Status
You acknowledge that BuildSmart is developed as an academic capstone project and may be provided in a developmental or prototype state. Features may be incomplete, data may not persist, and the Service may be modified or discontinued without notice.

---

## 11. INDEMNIFICATION

You agree to indemnify and hold harmless BuildSmart, its developers, and its academic institution from any claim, demand, loss, or liability (including reasonable legal fees) arising from:
- Your breach of these Terms;
- Your uploading of data you had no right to upload;
- Any quotation you issued to a third party;
- Your violation of any law or third-party right.

---

## 12. SUSPENSION, TERMINATION, AND DATA RETENTION

### 12.1 Termination by You
You may close your account at any time.

### 12.2 Suspension or Termination by Us
We may suspend or terminate your account, with or without notice, for breach of these Terms, unlawful use, or where required by law.

### 12.3 Effect of Termination
Upon termination, your right to access the Service ceases. We may delete Your Data after a reasonable period. **You are responsible for exporting any data you wish to retain before termination.**

### 12.4 Survival
Sections 3.3, 6, 7, 9, 10, 11, and 14 survive termination.

---

## 13. CHANGES TO THESE TERMS

We may revise these Terms. Material changes will be notified through the Service or by email. Continued use after changes take effect constitutes acceptance. If you do not accept revised Terms, you must stop using the Service.

---

## 14. GOVERNING LAW AND JURISDICTION

These Terms are governed by the laws of the **Republic of the Philippines**. Any dispute shall be submitted to the exclusive jurisdiction of the competent courts of the Philippines.

---

## 15. CONTACT

For questions regarding these Terms, data privacy requests, or to exercise your rights under RA 10173:

**[Insert contact email]**
**[Insert institution / developer name and address]**

---

## ACKNOWLEDGMENT

**BY CHECKING THE ACCEPTANCE BOX AND CREATING AN ACCOUNT, YOU CONFIRM THAT:**

1. You have read and understood these Terms;
2. You understand that **BuildSmart provides estimates, not certified professional outputs**;
3. You understand that **AI-generated segmentation, prices, and quotations may be wrong and require your independent verification**;
4. You accept sole responsibility for any quotation you issue and any commercial decision you make based on the Service;
5. You are authorized to bind the company you are registering.

✓ **I have read and agree to the BuildSmart Terms and Conditions and Privacy Notice.**
`;