CREATE TABLE IF NOT EXISTS site_condition_rule (
    site_condition_rule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    rule_name VARCHAR(150) NOT NULL,
    condition_field VARCHAR(50) NOT NULL,
    operator VARCHAR(10) NOT NULL CHECK (operator IN ('equals', 'gte', 'lte')),
    trigger_value VARCHAR(100) NOT NULL,
    scope_of_work VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    effective_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_site_condition_rule_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_site_condition_rule_company_status
    ON site_condition_rule (company_id, status, condition_field);

CREATE TABLE IF NOT EXISTS site_condition_rule_effect (
    site_condition_rule_effect_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_condition_rule_id INT NOT NULL,
    effect_key VARCHAR(80) NOT NULL,
    effect_type VARCHAR(30) NOT NULL CHECK (effect_type IN ('line_item', 'equipment', 'safety', 'productivity', 'schedule', 'warning')),
    label VARCHAR(150) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    pricing_method VARCHAR(30) NOT NULL CHECK (pricing_method IN ('fixed', 'per_sqm', 'labor_percentage', 'manual_review')),
    rate DECIMAL(12,2),
    percentage DECIMAL(7,4),
    schedule_days INT,
    CONSTRAINT fk_site_condition_effect_rule FOREIGN KEY (site_condition_rule_id) REFERENCES site_condition_rule(site_condition_rule_id) ON DELETE CASCADE,
    CONSTRAINT uq_site_condition_effect_key UNIQUE (site_condition_rule_id, effect_key)
);

CREATE TABLE IF NOT EXISTS project_site_condition (
    project_site_condition_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id INT NOT NULL,
    condition_field VARCHAR(50) NOT NULL,
    condition_value VARCHAR(100) NOT NULL,
    CONSTRAINT fk_project_site_condition_segment FOREIGN KEY (segment_id) REFERENCES project_segments(segment_id) ON DELETE CASCADE,
    CONSTRAINT uq_project_site_condition UNIQUE (segment_id, condition_field)
);

CREATE TABLE IF NOT EXISTS project_site_condition_effect_review (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id INT NOT NULL,
    site_condition_rule_id INT NOT NULL,
    effect_key VARCHAR(80) NOT NULL,
    included BOOLEAN NOT NULL DEFAULT TRUE,
    reviewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_site_condition_review_segment FOREIGN KEY (segment_id) REFERENCES project_segments(segment_id) ON DELETE CASCADE,
    CONSTRAINT fk_site_condition_review_rule FOREIGN KEY (site_condition_rule_id) REFERENCES site_condition_rule(site_condition_rule_id) ON DELETE CASCADE,
    CONSTRAINT uq_project_site_condition_effect_review UNIQUE (segment_id, site_condition_rule_id, effect_key)
);
