CREATE TABLE IF NOT EXISTS company_invites (
    invite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'Estimator' CHECK (role IN ('Admin', 'Estimator')),
    created_by INT NOT NULL,
    max_uses INT NOT NULL DEFAULT 1 CHECK (max_uses > 0),
    used_count INT NOT NULL DEFAULT 0 CHECK (used_count >= 0),
    expires_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_invites_company FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_invites_created_by FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_company_invites_used_count CHECK (used_count <= max_uses)
);
