CREATE TABLE IF NOT EXISTS site_condition_rule_effect (
    site_condition_rule_effect_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_condition_rule_id INT NOT NULL,
    effect_key VARCHAR(80) NOT NULL,
    effect_type VARCHAR(30) NOT NULL CHECK (effect_type IN ('line_item', 'equipment', 'safety', 'productivity', 'schedule', 'warning')),
    label VARCHAR(150) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    pricing_method VARCHAR(30) NOT NULL CHECK (pricing_method IN ('fixed', 'per_sqm', 'labor_percentage', 'manual_review')),
    rate DECIMAL(12,2),
    percentage DECIMAL(7,4),
    schedule_days INT,
    CONSTRAINT fk_site_condition_effect_rule FOREIGN KEY (site_condition_rule_id) REFERENCES site_condition_rule(site_condition_rule_id) ON DELETE CASCADE,
    CONSTRAINT uq_site_condition_effect_key UNIQUE (site_condition_rule_id, effect_key)
);

ALTER TABLE site_condition_rule
DROP COLUMN IF EXISTS effects;
