ALTER TABLE project_segments
    DROP COLUMN IF EXISTS project_adjustments;

CREATE TABLE IF NOT EXISTS project_segment_adjustment (
    project_segment_adjustment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id INT NOT NULL,
    condition VARCHAR(150) NOT NULL,
    amount DECIMAL(12,2) NOT NULL CHECK (amount >= 0),
    CONSTRAINT fk_project_segment_adjustment_segment FOREIGN KEY (segment_id) REFERENCES project_segments(segment_id) ON DELETE CASCADE,
    CONSTRAINT uq_project_segment_adjustment UNIQUE (segment_id, condition)
);

CREATE INDEX IF NOT EXISTS ix_project_segment_adjustment_segment
    ON project_segment_adjustment(segment_id);