CREATE TABLE IF NOT EXISTS quotation_breakdown_supplier_options (
    breakdown_supplier_option_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id INT NOT NULL,
    line_id VARCHAR(120) NOT NULL,
    supplier_id INT NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    brand VARCHAR(120),
    location VARCHAR(150),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    original_unit_price DECIMAL(12,2),
    quantity_available DECIMAL(12,2),
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('Uploaded', 'DPWH')),
    CONSTRAINT fk_breakdown_supplier_options_quote FOREIGN KEY (quote_id) REFERENCES quotation(quote_id) ON DELETE CASCADE,
    CONSTRAINT uq_breakdown_supplier_option UNIQUE (quote_id, line_id, supplier_id)
);

CREATE INDEX IF NOT EXISTS ix_breakdown_supplier_options_quote_line
    ON quotation_breakdown_supplier_options(quote_id, line_id);
