import re
import unicodedata


CITY_TO_REGION: dict[str, str] = {
    "caloocan": "NCR",
    "las pinas": "NCR",
    "makati": "NCR",
    "malabon": "NCR",
    "mandaluyong": "NCR",
    "manila": "NCR",
    "marikina": "NCR",
    "muntinlupa": "NCR",
    "navotas": "NCR",
    "paranaque": "NCR",
    "pasay": "NCR",
    "pasig": "NCR",
    "quezon": "NCR",
    "san juan": "NCR",
    "taguig": "NCR",
    "valenzuela": "NCR",
    "baguio": "CAR",
    "tabuk": "CAR",
    "alaminos": "Region I",
    "batac": "Region I",
    "candon": "Region I",
    "dagupan": "Region I",
    "laoag": "Region I",
    "san fernando": "Region I",
    "urdaneta": "Region I",
    "vigan": "Region I",
    "cauayan": "Region II",
    "ilagan": "Region II",
    "santiago": "Region II",
    "tuguegarao": "Region II",
    "angeles": "Region III",
    "balanga": "Region III",
    "baliwag": "Region III",
    "cabanatuan": "Region III",
    "gapan": "Region III",
    "mabalacat": "Region III",
    "malolos": "Region III",
    "meycauayan": "Region III",
    "munoz": "Region III",
    "olongapo": "Region III",
    "palayan": "Region III",
    "san jose": "Region III",
    "san jose del monte": "Region III",
    "tarlac": "Region III",
    "antipolo": "Region IV-A",
    "bacoor": "Region IV-A",
    "batangas": "Region IV-A",
    "binan": "Region IV-A",
    "cabuyao": "Region IV-A",
    "calaca": "Region IV-A",
    "calamba": "Region IV-A",
    "carmona": "Region IV-A",
    "cavite": "Region IV-A",
    "dasmarinas": "Region IV-A",
    "general trias": "Region IV-A",
    "imus": "Region IV-A",
    "lipa": "Region IV-A",
    "lucena": "Region IV-A",
    "san pablo": "Region IV-A",
    "san pedro": "Region IV-A",
    "santa rosa": "Region IV-A",
    "santo tomas": "Region IV-A",
    "tagaytay": "Region IV-A",
    "tanauan": "Region IV-A",
    "tayabas": "Region IV-A",
    "trece martires": "Region IV-A",
    "calapan": "Region IV-B",
    "puerto princesa": "Region IV-B",
    "iriga": "Region V",
    "legazpi": "Region V",
    "ligao": "Region V",
    "masbate": "Region V",
    "naga": "Region V",
    "sorsogon": "Region V",
    "tabaco": "Region V",
    "bacolod": "Region VI",
    "bago": "Region VI",
    "cadiz": "Region VI",
    "escalante": "Region VI",
    "himamaylan": "Region VI",
    "iloilo": "Region VI",
    "kabankalan": "Region VI",
    "la carlota": "Region VI",
    "passi": "Region VI",
    "roxas": "Region VI",
    "sagay": "Region VI",
    "silay": "Region VI",
    "sipalay": "Region VI",
    "victorias": "Region VI",
    "bais": "NIR",
    "bayawan": "NIR",
    "canlaon": "NIR",
    "dumaguete": "NIR",
    "guihulngan": "NIR",
    "tanjay": "NIR",
    "bogo": "Region VII",
    "carcar": "Region VII",
    "cebu": "Region VII",
    "danao": "Region VII",
    "lapu-lapu": "Region VII",
    "mandaue": "Region VII",
    "tagbilaran": "Region VII",
    "talisay": "Region VII",
    "toledo": "Region VII",
    "baybay": "Region VIII",
    "borongan": "Region VIII",
    "calbayog": "Region VIII",
    "catbalogan": "Region VIII",
    "maasin": "Region VIII",
    "ormoc": "Region VIII",
    "tacloban": "Region VIII",
    "dapitan": "Region IX",
    "dipolog": "Region IX",
    "isabela": "Region IX",
    "pagadian": "Region IX",
    "zamboanga": "Region IX",
    "cagayan de oro": "Region X",
    "el salvador": "Region X",
    "gingoog": "Region X",
    "iligan": "Region X",
    "malaybalay": "Region X",
    "oroquieta": "Region X",
    "ozamiz": "Region X",
    "tangub": "Region X",
    "valencia": "Region X",
    "davao": "Region XI",
    "digos": "Region XI",
    "mati": "Region XI",
    "panabo": "Region XI",
    "samal": "Region XI",
    "tagum": "Region XI",
    "general santos": "Region XII",
    "kidapawan": "Region XII",
    "koronadal": "Region XII",
    "tacurong": "Region XII",
    "bayugan": "Region XIII",
    "bislig": "Region XIII",
    "butuan": "Region XIII",
    "cabadbaran": "Region XIII",
    "surigao": "Region XIII",
    "tandag": "Region XIII",
    "cotabato": "BARMM",
    "lamitan": "BARMM",
    "marawi": "BARMM",
}


def _location_key(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_text = "".join(char for char in normalized if not unicodedata.combining(char))
    key = ascii_text.lower()
    key = re.sub(r"\b(city|deo|district engineering office)\b", " ", key)
    key = re.sub(r"[^a-z0-9-]+", " ", key)
    return re.sub(r"\s+", " ", key).strip()


def infer_region_from_location(location: str | None) -> str | None:
    if not location:
        return None
    key = _location_key(location)
    if not key:
        return None

    candidates = sorted(CITY_TO_REGION, key=len, reverse=True)
    for city in candidates:
        if re.search(rf"\b{re.escape(city)}\b", key):
            return CITY_TO_REGION[city]
    return None
