import type { Metadata } from "next";
import type { CSSProperties } from "react";
import { AuthProvider } from "@/providers/AuthProvider";
import "./globals.css";

const fontVariables = {
  "--font-sans": '"Avenir Next", "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  "--font-geist-mono": '"SFMono-Regular", "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
} as CSSProperties;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full antialiased"
      style={fontVariables}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
