import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/providers/AuthProvider";
import { DevAuthBypassPanel } from "@/components/dev/DevAuthBypassPanel";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AuthProvider>{children}</AuthProvider>
        {/* DEV-ONLY: never renders in production, see providers/dev-auth-bypass.ts */}
        {process.env.NODE_ENV === "development" && <DevAuthBypassPanel />}
      </body>
    </html>
  );
}
