// A representative (NOT exhaustive) list of major Philippine cities/municipalities, for a
// low-cost `<datalist>` autocomplete on address-style fields — no map/geocoding API, no
// external dependency. This is a fixed geographic taxonomy, not fabricated business data.
export const PH_CITIES = [
  'Quezon City',
  'Manila',
  'Caloocan',
  'Makati',
  'Pasig',
  'Taguig',
  'Pasay',
  'Mandaluyong',
  'Marikina',
  'Parañaque',
  'Las Piñas',
  'Muntinlupa',
  'Valenzuela',
  'Malabon',
  'Navotas',
  'San Juan',
  'Calamba',
  'Antipolo',
  'Bacoor',
  'Dasmariñas',
  'Imus',
  'San Pedro',
  'Biñan',
  'Santa Rosa',
  'Angeles City',
  'San Fernando (Pampanga)',
  'Malolos',
  'Meycauayan',
  'Baguio',
  'Dagupan',
  'Olongapo',
  'Batangas City',
  'Lipa',
  'Lucena',
  'Naga',
  'Legazpi',
  'Puerto Princesa',
  'Iloilo City',
  'Bacolod',
  'Roxas City',
  'Cebu City',
  'Mandaue',
  'Lapu-Lapu',
  'Tacloban',
  'Dumaguete',
  'Zamboanga City',
  'Cagayan de Oro',
  'Davao City',
  'General Santos',
  'Butuan',
  'Cotabato City',
  'Iligan',
  'Tuguegarao',
  'Baler',
] as const;
