import os
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import DeclarativeBase, sessionmaker

# .env lives at the repo root (shared with the Next.js frontend), one level up from backend/.
load_dotenv(Path(__file__).resolve().parents[2] / ".env")

DATABASE_URL = os.environ["DATABASE_URL"]

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    pass


def init_db() -> None:
    # Import model modules so their tables are registered on Base.metadata before
    # create_all runs. create_all only creates missing tables; it does not drop
    # or overwrite existing data.
    from app import models  # noqa: F401
    from app.ingest import models as ingest_models  # noqa: F401

    Base.metadata.create_all(bind=engine)

    try:
        with engine.begin() as connection:
            connection.execute(text("SET LOCAL lock_timeout = '1000ms'"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS color VARCHAR(50)"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS company_id INT"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS upload_id INT"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS color VARCHAR(50)"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS description VARCHAR(255)"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS company_id INT"))
            connection.execute(text("ALTER TABLE approved_match_cache ADD COLUMN IF NOT EXISTS company_id INT"))
            connection.execute(text("ALTER TABLE approved_match_cache DROP CONSTRAINT IF EXISTS uq_approved_match_cache_key"))
            connection.execute(
                text(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'uq_approved_match_cache_company_key'
                        ) THEN
                            ALTER TABLE approved_match_cache
                            ADD CONSTRAINT uq_approved_match_cache_company_key
                            UNIQUE (company_id, normalized_name, normalized_unit);
                        END IF;
                    END $$;
                    """
                )
            )
            connection.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS price_list_upload (
                        upload_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        company_id INT NOT NULL,
                        file_name VARCHAR(255) NOT NULL,
                        file_hash VARCHAR(64) NOT NULL,
                        file_size BIGINT,
                        source VARCHAR(20),
                        supplier_id INT,
                        quarter VARCHAR(2) CHECK (quarter IN ('Q1', 'Q2', 'Q3', 'Q4')),
                        year SMALLINT CHECK (year >= 2000),
                        upload_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        processing_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                            CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),
                        records_imported INT,
                        error_message TEXT,
                        CONSTRAINT uq_company_file_period UNIQUE (company_id, file_hash, quarter, year)
                    )
                    """
                )
            )
            connection.execute(
                text("CREATE INDEX IF NOT EXISTS idx_upload_company_status ON price_list_upload(company_id, processing_status)")
            )
            connection.execute(text("CREATE INDEX IF NOT EXISTS idx_upload_file_hash ON price_list_upload(file_hash)"))
    except OperationalError:
        # Startup should remain available; upload tasks have short lock timeouts
        # and will surface a clear failure if the DB is still locked.
        pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@contextmanager
def get_db_session():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
