import os
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import DeclarativeBase, sessionmaker

# .env lives at the repo root (shared with the Next.js frontend), one level up from backend/.
load_dotenv(Path(__file__).resolve().parents[2] / ".env")

DATABASE_URL = os.environ["DATABASE_URL"]

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    pass


def init_db() -> None:
    # Import model modules so their tables are registered on Base.metadata before
    # create_all runs. create_all only creates missing tables; it does not drop
    # or overwrite existing data.
    from app import models  # noqa: F401

    Base.metadata.create_all(bind=engine)

    try:
        with engine.begin() as connection:
            connection.execute(text("SET LOCAL lock_timeout = '1000ms'"))
            connection.execute(text("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255)"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS color VARCHAR(50)"))
            connection.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS client (
                        client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        company_id INT NOT NULL,
                        client_name VARCHAR(100) NOT NULL,
                        contact_person VARCHAR(100),
                        contact_email VARCHAR(100),
                        contact_number VARCHAR(20),
                        client_address VARCHAR(255),
                        profile_picture VARCHAR(255),
                        client_type VARCHAR(20) NOT NULL DEFAULT 'New'
                            CHECK (client_type IN ('New', 'Returning')),
                        notes TEXT,
                        status VARCHAR(20) NOT NULL DEFAULT 'Active'
                            CHECK (status IN ('Active', 'Inactive')),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_client_company
                            FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE
                    )
                    """
                )
            )
            connection.execute(text("ALTER TABLE client ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255)"))
            connection.execute(text("CREATE INDEX IF NOT EXISTS ix_client_company_status_name ON client (company_id, status, client_name)"))
            connection.execute(text("ALTER TABLE quotation ADD COLUMN IF NOT EXISTS client_id INT"))
            connection.execute(
                text(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_client_company') THEN
                            ALTER TABLE client ADD CONSTRAINT fk_client_company
                            FOREIGN KEY (company_id) REFERENCES company(company_id) ON DELETE CASCADE;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_quotation_client') THEN
                            ALTER TABLE quotation ADD CONSTRAINT fk_quotation_client
                            FOREIGN KEY (client_id) REFERENCES client(client_id) ON DELETE SET NULL;
                        END IF;
                    END $$;
                    """
                )
            )
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS company_id INT"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS upload_id INT"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS region VARCHAR(255)"))
            connection.execute(text("ALTER TABLE pricelist_review_item ADD COLUMN IF NOT EXISTS location VARCHAR(255)"))
            connection.execute(text("ALTER TABLE pricelist_review_item ALTER COLUMN raw_name TYPE VARCHAR(255)"))
            connection.execute(text("ALTER TABLE pricelist_review_item ALTER COLUMN suggested_material TYPE VARCHAR(255)"))
            connection.execute(text("ALTER TABLE pricelist_review_item ALTER COLUMN raw_price DROP NOT NULL"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS color VARCHAR(50)"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS description VARCHAR(255)"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS company_id INT"))
            connection.execute(text("ALTER TABLE items ADD COLUMN IF NOT EXISTS source_location VARCHAR(255)"))
            connection.execute(text("ALTER TABLE items ALTER COLUMN item_name TYPE VARCHAR(255)"))
            connection.execute(text("ALTER TABLE approved_match_cache ADD COLUMN IF NOT EXISTS company_id INT"))
            connection.execute(text("ALTER TABLE historical_price_record ADD COLUMN IF NOT EXISTS effective_date DATE"))
            connection.execute(text("ALTER TABLE historical_price_record ADD COLUMN IF NOT EXISTS location VARCHAR(255)"))
            connection.execute(
                text(
                    """
                    UPDATE historical_price_record
                    SET effective_date =
                        CASE
                            WHEN quarter = 'Q1' AND year IS NOT NULL THEN make_date(year, 1, 1)
                            WHEN quarter = 'Q2' AND year IS NOT NULL THEN make_date(year, 4, 1)
                            WHEN quarter = 'Q3' AND year IS NOT NULL THEN make_date(year, 7, 1)
                            WHEN quarter = 'Q4' AND year IS NOT NULL THEN make_date(year, 10, 1)
                            ELSE recorded_at::date
                        END
                    WHERE effective_date IS NULL
                    """
                )
            )
            connection.execute(text("ALTER TABLE historical_price_record ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE"))
            connection.execute(text("ALTER TABLE historical_price_record ALTER COLUMN effective_date SET NOT NULL"))
            connection.execute(text("ALTER TABLE historical_price_record DROP CONSTRAINT IF EXISTS uq_historical_price"))
            connection.execute(
                text(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'uq_historical_price'
                        ) THEN
                            ALTER TABLE historical_price_record
                            ADD CONSTRAINT uq_historical_price
                            UNIQUE (item_code, supplier_id, price_source, region, location, effective_date);
                        END IF;
                    END $$;
                    """
                )
            )
            connection.execute(text("CREATE INDEX IF NOT EXISTS ix_historical_price_effective_date ON historical_price_record (effective_date DESC)"))
            connection.execute(text("CREATE INDEX IF NOT EXISTS ix_historical_price_region_location ON historical_price_record (region, location)"))
            connection.execute(text("ALTER TABLE material_price_variance ADD COLUMN IF NOT EXISTS effective_date DATE"))
            connection.execute(
                text(
                    """
                    UPDATE material_price_variance
                    SET effective_date =
                        CASE
                            WHEN quarter = 'Q1' AND year IS NOT NULL THEN make_date(year, 1, 1)
                            WHEN quarter = 'Q2' AND year IS NOT NULL THEN make_date(year, 4, 1)
                            WHEN quarter = 'Q3' AND year IS NOT NULL THEN make_date(year, 7, 1)
                            WHEN quarter = 'Q4' AND year IS NOT NULL THEN make_date(year, 10, 1)
                            ELSE CURRENT_DATE
                        END
                    WHERE effective_date IS NULL
                    """
                )
            )
            connection.execute(text("ALTER TABLE material_price_variance ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE"))
            connection.execute(text("ALTER TABLE material_price_variance ALTER COLUMN effective_date SET NOT NULL"))
            connection.execute(text("ALTER TABLE material_price_variance DROP CONSTRAINT IF EXISTS uq_material_price_variance"))
            connection.execute(
                text(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'uq_material_price_variance'
                        ) THEN
                            ALTER TABLE material_price_variance
                            ADD CONSTRAINT uq_material_price_variance
                            UNIQUE (item_code, effective_date);
                        END IF;
                    END $$;
                    """
                )
            )
            connection.execute(text("CREATE INDEX IF NOT EXISTS ix_material_price_variance_effective_date ON material_price_variance (effective_date DESC)"))
            connection.execute(text("ALTER TABLE approved_match_cache DROP CONSTRAINT IF EXISTS uq_approved_match_cache_key"))
            connection.execute(
                text(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'uq_approved_match_cache_company_key'
                        ) THEN
                            ALTER TABLE approved_match_cache
                            ADD CONSTRAINT uq_approved_match_cache_company_key
                            UNIQUE (company_id, normalized_name, normalized_unit);
                        END IF;
                    END $$;
                    """
                )
            )
            connection.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS price_list_upload (
                        upload_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        company_id INT NOT NULL,
                        file_name VARCHAR(255) NOT NULL,
                        file_hash VARCHAR(64) NOT NULL,
                        file_size BIGINT,
                        source VARCHAR(20) CHECK (source IN ('DPWH', 'PSA', 'Supplier', 'Internal')),
                        supplier_id INT,
                        effective_date DATE NOT NULL DEFAULT CURRENT_DATE,
                        quarter VARCHAR(2) CHECK (quarter IN ('Q1', 'Q2', 'Q3', 'Q4')),
                        year SMALLINT CHECK (year >= 2000),
                        upload_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        processing_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                            CHECK (processing_status IN ('pending', 'processing', 'completed', 'failed')),
                        records_imported INT,
                        error_message TEXT
                    )
                    """
                )
            )
            connection.execute(text("ALTER TABLE price_list_upload ADD COLUMN IF NOT EXISTS effective_date DATE"))
            connection.execute(
                text(
                    """
                    UPDATE price_list_upload
                    SET effective_date =
                        CASE
                            WHEN quarter = 'Q1' AND year IS NOT NULL THEN make_date(year, 1, 1)
                            WHEN quarter = 'Q2' AND year IS NOT NULL THEN make_date(year, 4, 1)
                            WHEN quarter = 'Q3' AND year IS NOT NULL THEN make_date(year, 7, 1)
                            WHEN quarter = 'Q4' AND year IS NOT NULL THEN make_date(year, 10, 1)
                            ELSE upload_timestamp::date
                        END
                    WHERE effective_date IS NULL
                    """
                )
            )
            connection.execute(text("ALTER TABLE price_list_upload ALTER COLUMN effective_date SET DEFAULT CURRENT_DATE"))
            connection.execute(text("ALTER TABLE price_list_upload ALTER COLUMN effective_date SET NOT NULL"))
            connection.execute(text("ALTER TABLE price_list_upload DROP CONSTRAINT IF EXISTS uq_company_file_period"))
            connection.execute(text("ALTER TABLE price_list_upload DROP CONSTRAINT IF EXISTS uq_company_file_effective_date"))
            connection.execute(text("ALTER TABLE price_list_upload DROP CONSTRAINT IF EXISTS uq_company_file_supplier_effective_date"))
            connection.execute(
                text("CREATE INDEX IF NOT EXISTS idx_upload_company_status ON price_list_upload(company_id, processing_status)")
            )
            connection.execute(text("CREATE INDEX IF NOT EXISTS idx_upload_file_hash ON price_list_upload(file_hash)"))
            connection.execute(text("CREATE INDEX IF NOT EXISTS ix_price_list_upload_effective_date ON price_list_upload (effective_date DESC)"))
    except OperationalError:
        # Startup should remain available; upload tasks have short lock timeouts
        # and will surface a clear failure if the DB is still locked.
        pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@contextmanager
def get_db_session():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
